import { describe, it, expect } from "vitest";
import {
  validateGeneratedHtml,
  formatFailuresForRetry,
  isDarkColor,
  checkModeCoherence,
  SURFACE_CLASS_PAIRS,
  type ValidateGeneratedHtmlInput,
} from "./validate-generated-html";
import { VALIDATED_TEXT_PAIRS } from "@/lib/design/validated-text-pairs";
import { buildPalette, type Palette } from "@/lib/content/normalize-brand-colors";
import { generateStylesheet } from "@/lib/design/generate-stylesheet";
import { resolveTemplateTokens } from "@/lib/design/resolve-tokens";
import type { ManifestImage } from "./generate-markup";

// Task 3.5. Constraint 1: every check needs a test that fails on crafted bad input — a check
// that only ever sees good input is untested. Every describe block below pairs a passing case
// with at least one deliberately-broken case built specifically to trip that one check.
//
// Task 3.5a additions: role-scoped image reuse (logo may repeat, everything else may not) and
// checkGoogleFontsImport moved from scanning HTML for a <link> to scanning the real stylesheet
// (generate-stylesheet.ts's own output, which now genuinely emits an @import) for the real
// thing — both changes are reflected throughout this file, not bolted on at the end.

const REAL_PALETTE = buildPalette([{ hex: "#2563eb" }]);
const GOOGLE_FONTS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap";

// A real stylesheet, generated by the real 3.3 module — not a hand-crafted CSS string standing
// in for it. This is what makes check 8 reachable now (Task 3.5a): the @import genuinely exists
// in real output, not just in a fixture built to please this test.
const REAL_CSS = generateStylesheet({
  palette: REAL_PALETTE,
  tokens: resolveTemplateTokens(),
  googleFontsUrl: GOOGLE_FONTS_URL,
});

const ALLOWED_IMAGES: ManifestImage[] = [
  { assetId: "logo", url: "https://example.com/logo.png", role: "logo", widthPx: 200, heightPx: 60, subject: "graphic", altText: "Acme logo", focalPoint: { x: 0.5, y: 0.5 } },
  { assetId: "hero", url: "https://example.com/hero.jpg", role: "hero", widthPx: 1600, heightPx: 900, subject: "exterior", altText: "Storefront", focalPoint: { x: 0.5, y: 0.4 } },
  { assetId: "team", url: "https://example.com/team.jpg", role: "team", widthPx: 800, heightPx: 800, subject: "people", altText: "The team", focalPoint: { x: 0.5, y: 0.3 } },
];

const BASE_INPUT: ValidateGeneratedHtmlInput = {
  html: "",
  css: REAL_CSS,
  allowedImages: ALLOWED_IMAGES,
  palette: REAL_PALETTE,
  styleBundleMode: "light",
  typographyGoogleFontsUrl: GOOGLE_FONTS_URL,
};

// 3.4's own real output shape — body markup only, no <head>. The logo is deliberately used
// TWICE here (nav + footer), the exact real pattern Task 3.5's own end-to-end run found and
// this task's own instruction asks to permit — this fixture demonstrates the fix directly,
// not just in isolation.
const CLEAN_BODY_HTML = `
<header data-kondo-section="nav" class="surface-paper section"><div class="container"><img class="img" src="https://example.com/logo.png" alt="Acme logo" /></div></header>
<section data-kondo-section="hero" class="section surface-mist">
  <div class="container">
    <h1>Welcome</h1>
    <img class="img" src="https://example.com/hero.jpg" alt="Storefront" />
    <a class="btn btn--solid" href="/contact">Contact us</a>
  </div>
</section>
<footer data-kondo-section="footer" class="section surface-deep">
  <div class="container"><img class="img" src="https://example.com/logo.png" alt="Acme logo" /> Acme Inc.</div>
</footer>
`;

describe("validateGeneratedHtml — a fully clean, real-shaped concept is valid", () => {
  it("returns valid: true with a real palette, a real manifest, a real stylesheet, and the logo repeated in nav+footer", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    expect(result).toEqual({ valid: true });
  });
});

describe("check 1/8 — parses as well-formed HTML", () => {
  it("clean markup produces no well-formed-html failures", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "well-formed-html")).toEqual([]);
  });

  it("crafted bad input — a duplicate attribute — fails", () => {
    const bad = `<section data-kondo-section="hero" class="a" class="b">Hi</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: bad });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "well-formed-html" && f.message.includes("duplicate-attribute"))).toBe(true);
    }
  });

  it("crafted bad input — a null character — fails", () => {
    // Built via String.fromCharCode(0), not a literal byte typed into the source file — a
    // literal null byte embedded in a template literal proved fragile across this file's own
    // rewrites in this task (it silently vanished once when the file was rewritten and "Hi
    // there" was retyped as plain text), so it's constructed explicitly here instead of
    // relying on whatever byte a tool happens to preserve.
    const bad = `<section data-kondo-section="hero">Hi${String.fromCharCode(0)}there</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: bad });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "well-formed-html" && f.message.includes("unexpected-null-character"))).toBe(true);
    }
  });
});

describe("check 2/8 — every data-kondo-section marker present (the real thing, not auditMarkup)", () => {
  it("crafted bad input — a top-level section with no marker — fails, naming which one", () => {
    const bad = `<section data-kondo-section="hero">A</section><section>B, no marker</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: bad });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "section-markers" && f.message.includes("2 of 2"))).toBe(true);
    }
  });

  // The exact distinction 3.4's own auditMarkup couldn't make — a real, deeply nested <section>
  // inside a genuinely marked top-level section must NOT be flagged, because it isn't top-level.
  it("a nested, unmarked <section> (e.g. inside an FAQ accordion) is NOT flagged — this is the whole point of using a real DOM", () => {
    const html = `<section data-kondo-section="faq" class="section surface-paper">
      <div class="container">
        <section><h2>Q1</h2><p>A1</p></section>
        <section><h2>Q2</h2><p>A2</p></section>
      </div>
    </section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    if (!result.valid) {
      expect(result.failures.filter((f) => f.check === "section-markers")).toEqual([]);
    }
  });
});

describe("check 3/8 — banned tags, inline handlers, javascript:/data: URIs", () => {
  const cases: [string, string][] = [
    ["<script>", `<section data-kondo-section="hero"><script>alert(1)</script></section>`],
    ["<iframe>", `<section data-kondo-section="hero"><iframe src="https://x"></iframe></section>`],
    ["<object>", `<section data-kondo-section="hero"><object data="x"></object></section>`],
    ["<embed>", `<section data-kondo-section="hero"><embed src="x"></section>`],
    ["<form>", `<section data-kondo-section="hero"><form><input /></form></section>`],
    ["<meta http-equiv>", `<section data-kondo-section="hero"><meta http-equiv="refresh" content="0"></section>`],
    ["onclick=", `<section data-kondo-section="hero"><button onclick="alert(1)">Go</button></section>`],
    ["javascript: URI", `<section data-kondo-section="hero"><a href="javascript:alert(1)">Go</a></section>`],
  ];

  for (const [label, html] of cases) {
    it(`crafted bad input — ${label} — fails`, () => {
      const result = validateGeneratedHtml({ ...BASE_INPUT, html });
      expect(result.valid, label).toBe(false);
      if (!result.valid) expect(result.failures.some((f) => f.check === "banned-content"), label).toBe(true);
    });
  }

  it("clean markup produces no banned-content failures", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "banned-content")).toEqual([]);
  });
});

describe("check 4/8 — every image supplied; role-scoped reuse (Task 3.5a); nothing unusable", () => {
  it("crafted bad input — an invented image URL — fails", () => {
    const html = `<section data-kondo-section="hero"><img src="https://not-supplied.example.com/x.jpg" alt="x"></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.failures.some((f) => f.check === "image-provenance" && f.message.includes("not in the supplied"))).toBe(true);
  });

  // The rule Task 3.5a's own instruction asks for, stated in code and proven both ways: logo
  // reuse is fine, everything else is not.
  it("the logo used three times is NOT flagged — reuse is permitted for role: logo", () => {
    const html = `<header data-kondo-section="nav"><img src="https://example.com/logo.png" alt="a"></header>` +
      `<section data-kondo-section="hero"><img src="https://example.com/logo.png" alt="a"></section>` +
      `<footer data-kondo-section="footer"><img src="https://example.com/logo.png" alt="a"></footer>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "image-provenance")).toEqual([]);
  });

  it("crafted bad input — a non-logo image (the hero) used twice — fails, naming its role", () => {
    const html = `<section data-kondo-section="hero"><img src="https://example.com/hero.jpg" alt="a"><img src="https://example.com/hero.jpg" alt="a again"></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "image-provenance" && f.message.includes("more than once") && f.message.includes("role: hero"))).toBe(true);
    }
  });

  it("crafted bad input — the team photo used twice — fails the same way (any non-logo role, not just hero)", () => {
    const html = `<section data-kondo-section="about"><img src="https://example.com/team.jpg" alt="a"><img src="https://example.com/team.jpg" alt="a again"></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.failures.some((f) => f.check === "image-provenance" && f.message.includes("role: team"))).toBe(true);
  });

  it("an image marked unusable (excluded from the manifest, per 3.4's own buildImageManifest) fails the same way as an invented one", () => {
    // Simulates 3.4's own contract: an "unusable" asset never appears in allowedImages at all,
    // so referencing it looks identical to inventing a URL — by construction, not a separate
    // code path this test needs to fake up differently.
    const html = `<section data-kondo-section="hero"><img src="https://example.com/unusable-blurry-photo.jpg" alt="x"></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html, allowedImages: ALLOWED_IMAGES.filter((i) => i.role !== "hero") });
    expect(result.valid).toBe(false);
  });

  it("clean markup (logo repeated, every other image once) passes", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "image-provenance")).toEqual([]);
  });
});

describe("check 5/8 — contrast >= 4.5:1 on every text/background pair used", () => {
  it("SURFACE_CLASS_PAIRS names exactly pairs 1.6/3.3 already validated — cross-checked against the canonical list, not a fourth hand-copied version", () => {
    const validatedKeys = new Set(VALIDATED_TEXT_PAIRS.map((p) => `${p.fg}/${p.bg}`));
    for (const [cls, pair] of Object.entries(SURFACE_CLASS_PAIRS)) {
      expect(validatedKeys.has(`${pair.fg}/${pair.bg}`), cls).toBe(true);
    }
  });

  it("crafted bad input — an inline style setting colour — fails regardless of the actual computed ratio", () => {
    const html = `<section data-kondo-section="hero" style="color: #000000; background: #010101">Unreadable in practice, but that's not why this fails</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.failures.some((f) => f.check === "contrast" && f.message.includes("Inline style"))).toBe(true);
  });

  it("crafted bad input — a genuinely unsafe palette (ink === paper) with real markup — the ratio is actually computed, not assumed", () => {
    const badPalette: Palette = { ...REAL_PALETTE, ink: REAL_PALETTE.paper };
    const html = `<section data-kondo-section="hero" class="surface-paper">Low contrast</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html, palette: badPalette });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "contrast" && f.message.includes("surface-paper"))).toBe(true);
    }
  });

  it("clean markup with a real, currently-safe palette passes", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "contrast")).toEqual([]);
  });
});

describe("check 6/8 — mode coherence (Task 3.3a carry-forward, item 2)", () => {
  // checkModeCoherence is exported and called directly here, not through the full
  // validateGeneratedHtml pipeline — a hand-built synthetic Palette (below) is internally
  // inconsistent by construction (only `paper` is overridden; every other role still assumes a
  // light `paper`), so running it through every check at once would also trip contrast for
  // unrelated reasons and muddy exactly what this test is isolating. A real, non-obvious bug
  // this test setup caught in itself before it shipped: an earlier version of this test called
  // the full pipeline with that same synthetic palette and failed on "contrast", not
  // "mode-coherence" — the palette really was internally contradictory, not just the mode field
  // — fixed by testing checkModeCoherence in true isolation instead of loosening what counts as
  // a pass.

  // Task 3.3's own light bundles all correctly cohere with buildPalette's real output today.
  it("a real palette (light) against a light-mode bundle coheres", () => {
    expect(checkModeCoherence(REAL_PALETTE, "light")).toEqual([]);
  });

  // The synthetic fixture Task 3.5's own constraint 4 asked for — buildPalette can never
  // currently produce a dark `paper` (it's a hardcoded "#ffffff" literal, confirmed by reading
  // normalize-brand-colors.ts directly — never hue-derived, for any input), and no real style
  // bundle declares "dark" (3.3's own log entry: all 6 are "light"). This task's own log entry
  // records that the palette side is the deeper, more fundamental blocker of the two — a
  // palette-derivation gap, not a bundle-authoring one — see that entry for the reclassification.
  it("crafted bad input — a hand-built dark palette against a light-mode bundle — fails with the optometry-bug message", () => {
    const darkPalette: Palette = { ...REAL_PALETTE, paper: "#0a0a0a" };
    const failures = checkModeCoherence(darkPalette, "light");
    expect(failures).toHaveLength(1);
    expect(failures[0].check).toBe("mode-coherence");
    expect(failures[0].message).toContain("optometry-bug");
  });

  it("a hand-built dark palette against a hand-built dark-mode bundle coheres (both dark, no mismatch)", () => {
    const darkPalette: Palette = { ...REAL_PALETTE, paper: "#0a0a0a" };
    expect(checkModeCoherence(darkPalette, "dark")).toEqual([]);
  });

  it("isDarkColor: a known-dark and known-light hex resolve as expected", () => {
    expect(isDarkColor("#0a0a0a")).toBe(true);
    expect(isDarkColor("#ffffff")).toBe(false);
  });
});

describe("check 7/8 — no empty sections", () => {
  it("crafted bad input — a marked section with no text and no image — fails", () => {
    const html = `<section data-kondo-section="hero"><div class="container"></div></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.failures.some((f) => f.check === "empty-sections")).toBe(true);
  });

  it("a section with only an image (no text) is NOT empty", () => {
    const html = `<section data-kondo-section="hero"><img class="img" src="https://example.com/hero.jpg" alt="x"></section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "empty-sections")).toEqual([]);
  });

  it("clean markup has no empty sections", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "empty-sections")).toEqual([]);
  });
});

describe("check 8/8 — Google Fonts import matches the chosen pairing (Task 3.5a: now checks the stylesheet, not the markup)", () => {
  it("crafted bad input — a stylesheet with no @import at all — fails", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, css: ":root { --accent: red; }", html: CLEAN_BODY_HTML });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      expect(result.failures.some((f) => f.check === "google-fonts-import" && f.message.includes("No @import"))).toBe(true);
    }
  });

  it("crafted bad input — an @import present but for the wrong pairing — fails", () => {
    const wrongCss = `@import url("https://fonts.googleapis.com/css2?family=WrongFont");\n` + REAL_CSS;
    const result = validateGeneratedHtml({ ...BASE_INPUT, css: wrongCss, html: CLEAN_BODY_HTML });
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.failures.some((f) => f.check === "google-fonts-import" && f.message.includes("does not match"))).toBe(true);
  });

  it("the real stylesheet's own @import (Task 3.5a's fix) passes this check — reachable against real 3.3 output, not just a fixture built to please this test", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: CLEAN_BODY_HTML });
    if (!result.valid) expect(result.failures.filter((f) => f.check === "google-fonts-import")).toEqual([]);
  });
});

describe("validateGeneratedHtml — aggregates every failing check in one pass, not first-fail-wins", () => {
  it("markup broken in three unrelated ways surfaces all three", () => {
    const html = `<section data-kondo-section="hero"><script>alert(1)</script><img src="https://not-supplied.example.com/x.jpg" alt="x"></section><section>no marker</section>`;
    const result = validateGeneratedHtml({ ...BASE_INPUT, html });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      const checks = new Set(result.failures.map((f) => f.check));
      expect(checks.has("banned-content")).toBe(true);
      expect(checks.has("section-markers")).toBe(true);
      expect(checks.has("image-provenance")).toBe(true);
    }
  });
});

describe("formatFailuresForRetry — the interface 3.4's retry loop would consume (constraint 3)", () => {
  it("joins every failure into one string carrying both the check id and the specific message", () => {
    const result = validateGeneratedHtml({ ...BASE_INPUT, html: `<section>no marker</section>` });
    expect(result.valid).toBe(false);
    if (!result.valid) {
      const note = formatFailuresForRetry(result.failures);
      expect(note).toContain("[section-markers]");
      expect(typeof note).toBe("string");
      // Shape-compatible with generate-markup.ts's own correctionNote interpolation:
      // `IMPORTANT: your previous attempt was rejected: ${correctionNote}. Try again...`
      const rendered = `IMPORTANT: your previous attempt was rejected: ${note}. Try again, following every rule.`;
      expect(rendered.startsWith("IMPORTANT:")).toBe(true);
    }
  });
});
