// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // The CLI (migrate/introspect) connects directly, bypassing the pgbouncer pooler —
  // the app's runtime PrismaClient (lib/prisma.ts) uses the pooled DATABASE_URL instead.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
