import { buildAuditSummaryLines, type PromptInput } from "./types";

export function buildWordPressThemePromptText(input: PromptInput): string {
  const lines: string[] = [
    "You are generating a complete, installable WordPress theme for a JRNY Digital client, converting their existing coded site into WordPress. This is a code-to-WordPress transfer, based on a static analysis of their uploaded source repository.",
    "",
    "IMPORTANT: the client will edit their page content themselves later, in the WordPress editor (Gutenberg/block editor). Your job is the theme — the visual skin, typography, colors, header/footer/navigation chrome, and page templates — NOT fabricated marketing copy. Page and post templates MUST render real WordPress content via the Loop (the_content()) rather than hardcoded text, so whatever the client writes in WP Admin shows up correctly inside your design.",
    "",
    ...buildAuditSummaryLines(input),
  ];

  if (input.assetList.length > 0) {
    lines.push(
      'Logo images (if any) are attached below as images — reference them at "assets/{filename}" and wire them up as the custom logo (add_theme_support("custom-logo")) with a fallback to the site title/bloginfo("name") when no logo is set.'
    );
  }

  lines.push("\n## Required files");
  lines.push(
    `- style.css — MUST begin with a standard WordPress theme header comment block, e.g.:\n/*\nTheme Name: ${input.clientName}\nTheme URI: \nAuthor: JRNY Digital\nAuthor URI: https://jrnydigital.com.au\nDescription: Custom theme generated by Kondo for ${input.clientName}.\nVersion: 1.0\n*/\nfollowed by the theme's actual CSS.`
  );
  lines.push(
    "- functions.php — theme setup: add_theme_support for title-tag, post-thumbnails, html5, custom-logo; register a primary nav menu location; enqueue style.css (and script.js if you include one) via wp_enqueue_scripts, not hardcoded <link>/<script> tags."
  );
  lines.push(
    "- header.php — <!DOCTYPE html> through the opening of <body>/site wrapper; call wp_head() before </head>; site branding via the_custom_logo()/bloginfo('name'); primary navigation via wp_nav_menu() with a sensible fallback (e.g. wp_page_menu()) if no menu is assigned yet."
  );
  lines.push(
    "- footer.php — footer content and closing markup; call wp_footer() before </body></html>."
  );
  lines.push(
    "- index.php — fallback template: the standard WordPress Loop (have_posts()/the_post()) rendering the_title() and the_content(), styled to match the brand."
  );
  lines.push(
    "- front-page.php — the home page template. Still render the_content() from the Loop as the actual editable body (so the client's homepage content is editable in WP), wrapped in your themed header/hero chrome (e.g. a styled container) rather than fabricated hero copy."
  );
  lines.push(
    "- page.php — generic static page template: themed chrome around the Loop's the_content(), for any other pages the client creates."
  );

  lines.push("\n## Output rules");
  lines.push(
    "- This must be a real, valid, installable WordPress theme — no external CSS/JS framework or component-library CDN dependencies; assets are enqueued via functions.php. The one exception is the Google Fonts `<link>` tag specified by the design standards below — enqueue it via wp_enqueue_style() pointed at the Google Fonts URL rather than hardcoding a <link> tag."
  );
  lines.push(
    "- Preserve the brand's detected color palette and typography where sensible; use CSS custom properties for the palette."
  );
  lines.push(
    "- Use semantic HTML, template tags (get_header(), get_footer(), wp_head(), wp_footer(), the_content(), etc.) correctly per WordPress conventions — this will be installed on a real WordPress site."
  );
  lines.push(
    "- Do not fabricate photographic imagery — use CSS gradients, shapes, or simple inline SVG icons instead of placeholder photos, unless a logo asset is attached."
  );
  lines.push(
    "- Typography is a craft, not just a font choice: build a real heading hierarchy (h1-h3 should differ in weight/color/letter-spacing, not just size), and use bold/italic emphasis on the one or two phrases per section that earn it. A page where every paragraph is one uniform weight reads as unfinished."
  );
  lines.push(
    "- Treat every visual dimension of the theme as a deliberate decision, not a default: color palette, font pairing and heading hierarchy, spacing scale, shadows, gradients, corner radius, image treatment, motion and page transitions, and mobile layout. The design standards below give current, concrete guidance for each of these per archetype — use it instead of reaching for the safest generic choice (soft gray shadow, 8px radius everywhere, no gradient, desktop-shrunk-to-mobile) on any of them."
  );

  if (input.priorFiles && input.priorFiles.length > 0) {
    lines.push("\n## Current generated theme files (to be edited, not replaced from scratch)");
    for (const f of input.priorFiles) {
      lines.push(`\n### ${f.path}\n\`\`\`\n${f.content}\n\`\`\``);
    }
    lines.push("\n## Requested change");
    lines.push(input.userPrompt?.trim() || "Refine and improve the current theme.");
    lines.push(
      "\nReturn the FULL updated set of files reflecting this change, including any files left unchanged."
    );
  } else {
    lines.push("\n## Task");
    lines.push("Generate the first version of the WordPress theme now.");
    if (input.userPrompt?.trim()) {
      lines.push(`Additional instruction for this first pass: ${input.userPrompt.trim()}`);
    }
  }

  return lines.join("\n");
}
