import { buildAuditSummaryLines, type PromptInput } from "./types";

export function buildWordPressThemePromptText(input: PromptInput): string {
  const lines: string[] = [
    "You are building a complete, installable WordPress theme for a JRNY Digital client, converting their existing coded site into WordPress. This is a code-to-WordPress transfer, based on a static analysis of their uploaded source repository. The design direction below has already been decided and approved by the team — your job is to execute it faithfully in the theme, not to make a second round of design decisions.",
    "",
    "IMPORTANT: the client will edit their page content themselves later, in the WordPress editor (Gutenberg/block editor). Your job is the theme — the visual skin, typography, colors, header/footer/navigation chrome, and page templates — NOT fabricated marketing copy. Page and post templates MUST render real WordPress content via the Loop (the_content()) rather than hardcoded text, so whatever the client writes in WP Admin shows up correctly inside your design.",
    "",
    ...buildAuditSummaryLines(input),
  ];

  if (input.assetList.length > 0) {
    lines.push(
      'Logo and any real content images crawled from the client\'s current site are attached below as images, each labeled with the exact filename. Wire the logo up as the custom logo (add_theme_support("custom-logo")) with a fallback to the site title/bloginfo("name") when no logo is set. Reference content images at get_template_directory_uri() . "/assets/{filename}" wherever a section calls for a real photo — prefer a real attached image over a fabricated CSS placeholder wherever one fits.'
    );
  }

  lines.push("\n## Required files");
  lines.push(
    `- style.css — MUST begin with a standard WordPress theme header comment block, e.g.:\n/*\nTheme Name: ${input.clientName}\nTheme URI: \nAuthor: JRNY Digital\nAuthor URI: https://jrnydigital.com.au\nDescription: Custom theme generated by Kondo for ${input.clientName}.\nVersion: 1.0\n*/\nfollowed by the theme's actual CSS.`
  );
  lines.push(
    "- functions.php — theme setup: add_theme_support for title-tag, post-thumbnails, html5, custom-logo; register a primary nav menu location; enqueue style.css (and script.js if you include one) via wp_enqueue_scripts, not hardcoded <link>/<script> tags."
  );
  lines.push(
    "- header.php — <!DOCTYPE html> through the opening of <body>/site wrapper; call wp_head() before </head>; site branding via the_custom_logo()/bloginfo('name'); primary navigation via wp_nav_menu() with a sensible fallback (e.g. wp_page_menu()) if no menu is assigned yet."
  );
  lines.push(
    "- footer.php — footer content and closing markup; call wp_footer() before </body></html>."
  );
  lines.push(
    "- index.php — fallback template: the standard WordPress Loop (have_posts()/the_post()) rendering the_title() and the_content(), styled to match the brand."
  );
  lines.push(
    "- front-page.php — the home page template. Still render the_content() from the Loop as the actual editable body (so the client's homepage content is editable in WP), wrapped in your themed header/hero chrome (e.g. a styled container) rather than fabricated hero copy."
  );
  lines.push(
    "- page.php — generic static page template: themed chrome around the Loop's the_content(), for any other pages the client creates."
  );

  lines.push("\n## Output rules");
  lines.push(
    "- This must be a real, valid, installable WordPress theme — no external CSS/JS framework or component-library CDN dependencies; assets are enqueued via functions.php. The one exception is a Google Fonts link if the spec's type source is \"google\" — enqueue it via wp_enqueue_style() pointed at the Google Fonts URL rather than hardcoding a <link> tag."
  );
  lines.push(
    "- Define the spec's palette, type scale, and spacing scale as CSS custom properties; never hardcode a hex value or font family outside that block."
  );
  lines.push(
    "- Use semantic HTML, template tags (get_header(), get_footer(), wp_head(), wp_footer(), the_content(), etc.) correctly per WordPress conventions — this will be installed on a real WordPress site."
  );

  if (input.priorFiles && input.priorFiles.length > 0) {
    lines.push("\n## Current generated theme files (to be edited, not replaced from scratch)");
    for (const f of input.priorFiles) {
      lines.push(`\n### ${f.path}\n\`\`\`\n${f.content}\n\`\`\``);
    }
    lines.push("\n## Requested change");
    lines.push(input.userPrompt?.trim() || "Refine and improve the current theme.");
    lines.push(
      "\nThe approved design spec above still governs palette/type/layout/motion — apply the requested change within it unless the change explicitly asks to alter the direction itself."
    );
    lines.push(
      "\nReturn the FULL updated set of files reflecting this change, including any files left unchanged."
    );
  } else {
    lines.push("\n## Task");
    lines.push("Generate the first version of the WordPress theme now, executing the approved spec.");
    if (input.userPrompt?.trim()) {
      lines.push(`Additional instruction for this first pass: ${input.userPrompt.trim()}`);
    }
  }

  return lines.join("\n");
}
